name: chat
description: Chat rooms app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.72+161

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  firebase_core: ^3.4.0
  firebase_analytics: ^11.3.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  firebase_crashlytics: ^4.1.0
  firebase_messaging: ^15.1.0
  firebase_storage: ^12.2.0
  firebase_database: ^11.1.1
  firebase_performance: ^0.10.0+5
  cloud_functions: ^5.1.0
  flutter_i18n: ^0.36.2
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
  shared_preferences: ^2.2.3
  crypto: ^3.0.3
  cached_network_image: ^3.4.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.1
  giphy_get: ^3.5.6
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  flutter_markdown: ^0.7.3+1
  extended_image: ^8.2.4
  universal_io: ^2.2.2
  http: ^1.2.2
  flutter_app_badger: ^1.5.0
  soundpool: ^2.4.1
  google_mobile_ads: ^5.1.0
  in_app_review: ^2.0.9
  # Only added because web fails else for unknown reasons
  extended_image_library: ^4.0.5
  flutter_holo_date_picker: ^2.0.0
  html_unescape: ^2.0.0
  google_api_headers: ^3.2.0
  blur: ^3.1.0
  collection: ^1.18.0
  purchases_flutter: ^8.1.2
  flutter_nude_detector: ^0.0.4+1
  intl: ^0.18.1 
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/flutter_i18n/
    - assets/html/
    - assets/img/
    - assets/lottie/
    - assets/ml_models/
